const sponsorContainer = document.querySelector(".sponsors-container");

const sponsorContent = {
  name: [
    "MTV Beats",
    "CocaCola",
    "Bingo",
    "RozDhan",
    "Zebronics",
    "RedFm",
    "Ankur Arora",
    "Honda",
    "Amul",
    "KTM",
    "Ease My Trip",
    "Mood Indigo",
    "Hindustan Times",
    "Axis Bank",
    "Spartan Poker",
    "College Duniya",
    "State Bank Of India",
    "Canara Bank",
    "Swiggy",
    "Clickography",
    "Resonance Studios",
    "Grapevine",
    "Punjab National Bank",
    "Indian Overseas Bank",
    "Ed Times",
    "Allahabad Dance Centre",
    "HDFC Bank",
    "ICICI Bank",
    "Syndicate Bank",
    "CarHP",
    "Zoutons",
    "DU beat",
    "Max",
    "Direct Bollywood",
    "BlogAdda",
    "Awesong",
    "Souled Store",
    "Lensfit",
    "Dare2compete",
    "Insight One",
    "WAC",
    "Selcouth India Labs",
    "DU Express",
    "Oh Campus",
    "Grab On",
    "Chords & Co.",
    "FundaMakers",
    "Design Boat",
  ],

  imagePath: [
    "./img/sponsors/mtv.jpg",
    "./img/sponsors/cocacola.png",
    "./img/sponsors/bingo.png",
    "./img/sponsors/rozdhan.png",
    "./img/sponsors/zebronics.png",
    "./img/sponsors/redfm.png",
    "./img/sponsors/ankur.jpg",
    "./img/sponsors/honda.png",
    "./img/sponsors/amul.png",
    "./img/sponsors/ktm.png",
    "./img/sponsors/ease.png",
    "./img/sponsors/mood.png",
    "./img/sponsors/ht.png",
    "./img/sponsors/axis.png",
    "./img/sponsors/spartan.png",
    "./img/sponsors/collegeduniya.png",
    "./img/sponsors/sbi.png",
    "./img/sponsors/canara.png",
    "./img/sponsors/swiggy.png",
    "./img/sponsors/click.jpg",
    "./img/sponsors/resonance.png",
    "./img/sponsors/grapevine.png",
    "./img/sponsors/punjabbank.png",
    "./img/sponsors/overbank.png",
    "./img/sponsors/ed.jpg",
    "./img/sponsors/dancecentre.jpg",
    "./img/sponsors/hdfc.png",
    "./img/sponsors/icici.png",
    "./img/sponsors/Syndicate.png",
    "./img/sponsors/carhp.jpg",
    "./img/sponsors/zoutons.jpg",
    "./img/sponsors/dubeat.png",
    "./img/sponsors/max.png",
    "./img/sponsors/bollywood.png",
    "./img/sponsors/blogadda.png",
    "./img/sponsors/Awesong.png",
    "./img/sponsors/souled-store.png",
    "./img/sponsors/lensfit.png",
    "./img/sponsors/dare2.png",
    "./img/sponsors/insightone.jpg",
    "./img/sponsors/wac.png",
    "./img/sponsors/sel.jpg",
    "./img/sponsors/du.png",
    "./img/sponsors/ohio.jpg",
    "./img/sponsors/GrabOn.png",
    "./img/sponsors/C&C.jpg",
    "./img/sponsors/fundamakers.png",
    "./img/sponsors/designboat.png",
  ],
  title: [
    "Powered By",
    "Associate Partner",
    "Entertainment Partner",
    "Official Infotainment Partner",
    "Audio Partner",
    "Radio Partner",
    "Clothing Partner",
    "Mobility Partner",
    "Dairy Partner",
    "Driven By Partner",
    "Official Travel Partner",
    "Talent Showcase Partner",
    "Official Media Partner",
    "Banking Partner",
    "Poker Partner",
    "Media Partner",
    "Banking Partner",
    "Banking Partner",
    "Food Delivery Partner",
    "Official Photography Partner",
    "Recording Partner",
    "Youth Partner",
    "Banking Partner",
    "Banking Partner",
    "Media Partner",
    "Stage Event Partner",
    "Banking Partner",
    "Bank Partner",
    "Bank Partner",
    "Media Partner",
    "Media Partner",
    "Media Partner",
    "Fashion Partner",
    "Online Media Partner",
    "Blogger Outreach Partner",
    "Online Media Partner",
    "Gifting Partner",
    "Official Lens Partner",
    "Online Event Hosting Partner",
    "Youth Partner",
    "Workshop Partner",
    "Media Partner",
    "Media Partner",
    "Media Partner",
    "Media Partner",
    "Associate for Clangour & Cadence",
    "CAT Partner",
    "Design for Hackathon",
  ],
};
for (let i = 0; i < sponsorContent.name.length; ++i) {
  sponsorContainer.innerHTML += `
<div class="sponsor-card">
  <img src="${sponsorContent.imagePath[i]}" />
  <br />
  <span class="sponsor-name"> ${sponsorContent.name[i]}</span>
  <span class="sponsor-title">${sponsorContent.title[i]}</span>
</div>
`;
}
